export enum MaterialIconsEnum {
    Business = "business",
    Movie = "movie",
    HealthAndSafety = "health-and-safety",
    Science = "science",
    Sports = "sports",
    Computer = "computer",
    Newspaper = "newspaper",
    MedicalServices = "medical-services",
    MonetizationOn = "monetization-on",
    Restaurant = "restaurant",
    Flight = "flight",
    MusicNote = "music-note",
    TV = "tv",
    Book = "book",
    VideogameAsset = "videogame-asset",
    Pets = "pets",
    DirectionsCar = "directions-car",
}